# Generated by Django 3.2.7 on 2021-09-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_auto_20210906_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='location_id',
        ),
    ]
